# Generated by Django 4.1.4 on 2023-11-05 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pommento_core", "0002_page_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="ip",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
