# Generated by Django 4.1.4 on 2023-11-15 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pommento_core", "0005_comment_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="domain_intel",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="comment",
            name="embargo",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="comment",
            name="ip_intel",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="comment",
            name="malicious",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="comment",
            name="redact",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="comment",
            name="url_intel",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="comment",
            name="user_intel",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="page",
            name="slug",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name="PangeaService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "comment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pommento_core.comment",
                    ),
                ),
            ],
        ),
    ]
