# Generated by Django 4.1.4 on 2023-11-15 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pommento_core", "0006_comment_domain_intel_comment_embargo_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="url_intel",
        ),
        migrations.AddField(
            model_name="comment",
            name="url_intel_breach",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="comment",
            name="domain_intel",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="comment",
            name="embargo",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="comment",
            name="ip_intel",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="comment",
            name="user_intel",
            field=models.JSONField(default=dict),
        ),
        migrations.DeleteModel(
            name="PangeaService",
        ),
    ]
