# Generated by Django 4.1.4 on 2023-11-05 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pommento_auth", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
    ]
